### ISSUE TITLE
App responds to pull requests with POST http://localhost:3000/api/webhook - 200 on terminal  but I don't see any comment in the pull request

### ISSUE THREAD

**Issue by CloudInnovator** [github/github-app-js-sample#34]
Payload:
`{"event":"check_suite","payload":{"action":"requested","check_suite":{"id":20111238456,"node_id":"CS_kwDOLFDfWM8AAAAErrklOA","head_branch":"main","head_sha":"732428755f4f9d204d6d0479b2926d6c8eb3cc14","status":"queued","conclusion":null,"url":"https://api.github.com/repos/CloudInnovator/intall-test/check-suites/20111238456","before":"97193ff6b0241b7be13949c3ebbc38c26d3da583","after":"732428755f4f9d204d6d0479b2926d6c8eb3cc14","pull_requests":[],"app":{"id":796861,"slug":"cloudinnovator-allot","node_id":"A_kwDOBnh6tc4ADCi9","owner":{"login":"CloudInnovator","id":108559029,"node_id":"U_kgDOBnh6tQ","avatar_url":"https://avatars.githubusercontent.com/u/108559029?v=4","gravatar_id":"","url":"https://api.github.com/users/CloudInnovator","html_url":"https://github.com/CloudInnovator","followers_url":"https://api.github.com/users/CloudInnovator/followers","following_url":"https://api.github.com/users/CloudInnovator/following{/other_user}","gists_url":"https://api.github.com/users/CloudInnovator/gists{/gist_id}","starred_url":"https://api.github.com/users/CloudInnovator/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/CloudInnovator/subscriptions","organizations_url":"https://api.github.com/users/CloudInnovator/orgs","repos_url":"https://api.github.com/users/CloudInnovator/repos","events_url":"https://api.github.com/users/CloudInnovator/events{/privacy}","received_events_url":"https://api.github.com/users/CloudInnovator/received_events","type":"User","site_admin":false},"name":"cloudinnovator-allot","description":"","external_url":"https://github.com/MAU-Yola/allot","html_url":"https://github.com/apps/cloudinnovator-allot","created_at":"2024-01-14T21:21:12Z","updated_at":"2024-01-14T21:21:12Z","permissions":{"actions":"write","actions_variables":"write","administration":"write","checks":"write","codespaces":"write","codespaces_lifecycle_admin":"write","codespaces_metadata":"read","codespaces_secrets":"write","contents":"write","dependabot_secrets":"write","deployments":"write","discussions":"write","environments":"write","issues":"write","merge_queues":"write","metadata":"read","packages":"write","pages":"write","pull_requests":"write","repository_advisories":"write","repository_custom_properties":"write","repository_hooks":"write","repository_projects":"admin","secrets":"write","secret_scanning_alerts":"write","security_events":"write","statuses":"write","vulnerability_alerts":"write","workflows":"write"},"events":[]},"created_at":"2024-01-25T09:06:08Z","updated_at":"2024-01-25T09:06:08Z","rerequestable":true,"runs_rerequestable":true,"latest_check_runs_count":0,"check_runs_url":"https://api.github.com/repos/CloudInnovator/intall-test/check-suites/20111238456/check-runs","head_commit":{"id":"732428755f4f9d204d6d0479b2926d6c8eb3cc14","tree_id":"ff78c744644a8fdb2fb1dfd0255fbc4e54375d19","message":"Merge pull request #13 from CloudInnovator/new_pull_request_test\n\nfunction stripper_11","timestamp":"2024-01-25T09:06:05Z","author":{"name":"Ridwan Naibi Suleiman","email":"rid.sul.nai@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"}}},"repository":{"id":743497560,"node_id":"R_kgDOLFDfWA","name":"intall-test","full_name":"CloudInnovator/intall-test","private":true,"owner":{"login":"CloudInnovator","id":108559029,"node_id":"U_kgDOBnh6tQ","avatar_url":"https://avatars.githubusercontent.com/u/108559029?v=4","gravatar_id":"","url":"https://api.github.com/users/CloudInnovator","html_url":"https://github.com/CloudInnovator","followers_url":"https://api.github.com/users/CloudInnovator/followers","following_url":"https://api.github.com/users/CloudInnovator/following{/other_user}","gists_url":"https://api.github.com/users/CloudInnovator/gists{/gist_id}","starred_url":"https://api.github.com/users/CloudInnovator/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/CloudInnovator/subscriptions","organizations_url":"https://api.github.com/users/CloudInnovator/orgs","repos_url":"https://api.github.com/users/CloudInnovator/repos","events_url":"https://api.github.com/users/CloudInnovator/events{/privacy}","received_events_url":"https://api.github.com/users/CloudInnovator/received_events","type":"User","site_admin":false},"html_url":"https://github.com/CloudInnovator/intall-test","description":null,"fork":false,"url":"https://api.github.com/repos/CloudInnovator/intall-test","forks_url":"https://api.github.com/repos/CloudInnovator/intall-test/forks","keys_url":"https://api.github.com/repos/CloudInnovator/intall-test/keys{/key_id}","collaborators_url":"https://api.github.com/repos/CloudInnovator/intall-test/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/CloudInnovator/intall-test/teams","hooks_url":"https://api.github.com/repos/CloudInnovator/intall-test/hooks","issue_events_url":"https://api.github.com/repos/CloudInnovator/intall-test/issues/events{/number}","events_url":"https://api.github.com/repos/CloudInnovator/intall-test/events","assignees_url":"https://api.github.com/repos/CloudInnovator/intall-test/assignees{/user}","branches_url":"https://api.github.com/repos/CloudInnovator/intall-test/branches{/branch}","tags_url":"https://api.github.com/repos/CloudInnovator/intall-test/tags","blobs_url":"https://api.github.com/repos/CloudInnovator/intall-test/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/CloudInnovator/intall-test/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/CloudInnovator/intall-test/git/refs{/sha}","trees_url":"https://api.github.com/repos/CloudInnovator/intall-test/git/trees{/sha}","statuses_url":"https://api.github.com/repos/CloudInnovator/intall-test/statuses/{sha}","languages_url":"https://api.github.com/repos/CloudInnovator/intall-test/languages","stargazers_url":"https://api.github.com/repos/CloudInnovator/intall-test/stargazers","contributors_url":"https://api.github.com/repos/CloudInnovator/intall-test/contributors","subscribers_url":"https://api.github.com/repos/CloudInnovator/intall-test/subscribers","subscription_url":"https://api.github.com/repos/CloudInnovator/intall-test/subscription","commits_url":"https://api.github.com/repos/CloudInnovator/intall-test/commits{/sha}","git_commits_url":"https://api.github.com/repos/CloudInnovator/intall-test/git/commits{/sha}","comments_url":"https://api.github.com/repos/CloudInnovator/intall-test/comments{/number}","issue_comment_url":"https://api.github.com/repos/CloudInnovator/intall-test/issues/comments{/number}","contents_url":"https://api.github.com/repos/CloudInnovator/intall-test/contents/{+path}","compare_url":"https://api.github.com/repos/CloudInnovator/intall-test/compare/{base}...{head}","merges_url":"https://api.github.com/repos/CloudInnovator/intall-test/merges","archive_url":"https://api.github.com/repos/CloudInnovator/intall-test/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/CloudInnovator/intall-test/downloads","issues_url":"https://api.github.com/repos/CloudInnovator/intall-test/issues{/number}","pulls_url":"https://api.github.com/repos/CloudInnovator/intall-test/pulls{/number}","milestones_url":"https://api.github.com/repos/CloudInnovator/intall-test/milestones{/number}","notifications_url":"https://api.github.com/repos/CloudInnovator/intall-test/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/CloudInnovator/intall-test/labels{/name}","releases_url":"https://api.github.com/repos/CloudInnovator/intall-test/releases{/id}","deployments_url":"https://api.github.com/repos/CloudInnovator/intall-test/deployments","created_at":"2024-01-15T11:14:58Z","updated_at":"2024-01-24T10:10:35Z","pushed_at":"2024-01-25T09:06:06Z","git_url":"git://github.com/CloudInnovator/intall-test.git","ssh_url":"git@github.com:CloudInnovator/intall-test.git","clone_url":"https://github.com/CloudInnovator/intall-test.git","svn_url":"https://github.com/CloudInnovator/intall-test","homepage":null,"size":27,"stargazers_count":0,"watchers_count":0,"language":"JavaScript","has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"has_discussions":false,"forks_count":0,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":0,"license":null,"allow_forking":true,"is_template":false,"web_commit_signoff_required":false,"topics":[],"visibility":"private","forks":0,"open_issues":0,"watchers":0,"default_branch":"main"},"sender":{"login":"CloudInnovator","id":108559029,"node_id":"U_kgDOBnh6tQ","avatar_url":"https://avatars.githubusercontent.com/u/108559029?v=4","gravatar_id":"","url":"https://api.github.com/users/CloudInnovator","html_url":"https://github.com/CloudInnovator","followers_url":"https://api.github.com/users/CloudInnovator/followers","following_url":"https://api.github.com/users/CloudInnovator/following{/other_user}","gists_url":"https://api.github.com/users/CloudInnovator/gists{/gist_id}","starred_url":"https://api.github.com/users/CloudInnovator/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/CloudInnovator/subscriptions","organizations_url":"https://api.github.com/users/CloudInnovator/orgs","repos_url":"https://api.github.com/users/CloudInnovator/repos","events_url":"https://api.github.com/users/CloudInnovator/events{/privacy}","received_events_url":"https://api.github.com/users/CloudInnovator/received_events","type":"User","site_admin":false},"installation":{"id":46143917,"node_id":"MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNDYxNDM5MTc="}}}`

**Comment by tarebyte** [comment]
Also for future reference. The JSON payload would be much easier to read by using the language formatting block and an online formatter like:

```json
{
  "event": "check_suite",
  "payload": {
    "action": "requested",
    "check_suite": {
      "id": 20111238456,
      "node_id": "CS_kwDOLFDfWM8AAAAErrklOA",
      "head_branch": "main",
      "head_sha": "732428755f4f9d204d6d0479b2926d6c8eb3cc14",
      "status": "queued",
      "conclusion": null,
      "url": "https://api.github.com/repos/CloudInnovator/intall-test/check-suites/20111238456",
      "before": "97193ff6b0241b7be13949c3ebbc38c26d3da583",
      "after": "732428755f4f9d204d6d0479b2926d6c8eb3cc14",
      "pull_requests": [],
      "app": {
        "id": 796861,
        "slug": "cloudinnovator-allot",
        "node_id": "A_kwDOBnh6tc4ADCi9",
        "owner": {
          "login": "CloudInnovator",
          "id": 108559029,
          "node_id": "U_kgDOBnh6tQ",
          "avatar_url": "https://avatars.githubusercontent.com/u/108559029?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/CloudInnovator",
          "html_url": "https://github.com/CloudInnovator",
          "followers_url": "https://api.github.com/users/CloudInnovator/followers",
          "following_url": "https://api.github.com/users/CloudInnovator/following{/other_user}",
          "gists_url": "https://api.github.com/users/CloudInnovator/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/CloudInnovator/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/CloudInnovator/subscriptions",
          "organizations_url": "https://api.github.com/users/CloudInnovator/orgs",
          "repos_url": "https://api.github.com/users/CloudInnovator/repos",
          "events_url": "https://api.github.com/users/CloudInnovator/events{/privacy}",
          "received_events_url": "https://api.github.com/users/CloudInnovator/received_events",
          "type": "User",
          "site_admin": false
        },
        "name": "cloudinnovator-allot",
        "description": "",
        "external_url": "https://github.com/MAU-Yola/allot",
        "html_url": "https://github.com/apps/cloudinnovator-allot",
        "created_at": "2024-01-14T21:21:12Z",
        "updated_at": "2024-01-14T21:21:12Z",
        "permissions": {
          "actions": "write",
          "actions_variables": "write",
          "administration": "write",
          "checks": "write",
          "codespaces": "write",
          "codespaces_lifecycle_admin": "write",
          "codespaces_metadata": "read",
          "codespaces_secrets": "write",
          "contents": "write",
          "dependabot_secrets": "write",
          "deployments": "write",
          "discussions": "write",
          "environments": "write",
          "issues": "write",
          "merge_queues": "write",
          "metadata": "read",
          "packages": "write",
          "pages": "write",
          "pull_requests": "write",
          "repository_advisories": "write",
          "repository_custom_properties": "write",
          "repository_hooks": "write",
          "repository_projects": "admin",
          "secrets": "write",
          "secret_scanning_alerts": "write",
          "security_events": "write",
          "statuses": "write",
          "vulnerability_alerts": "write",
          "workflows": "write"
        },
        "events": []
      },
      "created_at": "2024-01-25T09:06:08Z",
      "updated_at": "2024-01-25T09:06:08Z",
      "rerequestable": true,
      "runs_rerequestable": true,
      "latest_check_runs_count": 0,
      "check_runs_url": "https://api.github.com/repos/CloudInnovator/intall-test/check-suites/20111238456/check-runs",
      "head_commit": {
        "id": "732428755f4f9d204d6d0479b2926d6c8eb3cc14",
        "tree_id": "ff78c744644a8fdb2fb1dfd0255fbc4e54375d19",
        "message": "Merge pull request #13 from CloudInnovator/new_pull_request_test\n\nfunction stripper_11",
        "timestamp": "2024-01-25T09:06:05Z",
        "author": {
          "name": "Ridwan Naibi Suleiman",
          "email": "rid.sul.nai@gmail.com"
        },
        "committer": {
          "name": "GitHub",
          "email": "noreply@github.com"
        }
      }
    },
    "repository": {
      "id": 743497560,
      "node_id": "R_kgDOLFDfWA",
      "name": "intall-test",
      "full_name": "CloudInnovator/intall-test",
      "private": true,
      "owner": {
        "login": "CloudInnovator",
        "id": 108559029,
        "node_id": "U_kgDOBnh6tQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/108559029?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CloudInnovator",
        "html_url": "https://github.com/CloudInnovator",
        "followers_url": "https://api.github.com/users/CloudInnovator/followers",
        "following_url": "https://api.github.com/users/CloudInnovator/following{/other_user}",
        "gists_url": "https://api.github.com/users/CloudInnovator/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CloudInnovator/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CloudInnovator/subscriptions",
        "organizations_url": "https://api.github.com/users/CloudInnovator/orgs",
        "repos_url": "https://api.github.com/users/CloudInnovator/repos",
        "events_url": "https://api.github.com/users/CloudInnovator/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CloudInnovator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/CloudInnovator/intall-test",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/CloudInnovator/intall-test",
      "forks_url": "https://api.github.com/repos/CloudInnovator/intall-test/forks",
      "keys_url": "https://api.github.com/repos/CloudInnovator/intall-test/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/CloudInnovator/intall-test/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/CloudInnovator/intall-test/teams",
      "hooks_url": "https://api.github.com/repos/CloudInnovator/intall-test/hooks",
      "issue_events_url": "https://api.github.com/repos/CloudInnovator/intall-test/issues/events{/number}",
      "events_url": "https://api.github.com/repos/CloudInnovator/intall-test/events",
      "assignees_url": "https://api.github.com/repos/CloudInnovator/intall-test/assignees{/user}",
      "branches_url": "https://api.github.com/repos/CloudInnovator/intall-test/branches{/branch}",
      "tags_url": "https://api.github.com/repos/CloudInnovator/intall-test/tags",
      "blobs_url": "https://api.github.com/repos/CloudInnovator/intall-test/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/CloudInnovator/intall-test/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/CloudInnovator/intall-test/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/CloudInnovator/intall-test/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/CloudInnovator/intall-test/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/CloudInnovator/intall-test/languages",
      "stargazers_url": "https://api.github.com/repos/CloudInnovator/intall-test/stargazers",
      "contributors_url": "https://api.github.com/repos/CloudInnovator/intall-test/contributors",
      "subscribers_url": "https://api.github.com/repos/CloudInnovator/intall-test/subscribers",
      "subscription_url": "https://api.github.com/repos/CloudInnovator/intall-test/subscription",
      "commits_url": "https://api.github.com/repos/CloudInnovator/intall-test/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/CloudInnovator/intall-test/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/CloudInnovator/intall-test/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/CloudInnovator/intall-test/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/CloudInnovator/intall-test/contents/{+path}",
      "compare_url": "https://api.github.com/repos/CloudInnovator/intall-test/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/CloudInnovator/intall-test/merges",
      "archive_url": "https://api.github.com/repos/CloudInnovator/intall-test/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/CloudInnovator/intall-test/downloads",
      "issues_url": "https://api.github.com/repos/CloudInnovator/intall-test/issues{/number}",
      "pulls_url": "https://api.github.com/repos/CloudInnovator/intall-test/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/CloudInnovator/intall-test/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/CloudInnovator/intall-test/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/CloudInnovator/intall-test/labels{/name}",
      "releases_url": "https://api.github.com/repos/CloudInnovator/intall-test/releases{/id}",
      "deployments_url": "https://api.github.com/repos/CloudInnovator/intall-test/deployments",
      "created_at": "2024-01-15T11:14:58Z",
      "updated_at": "2024-01-24T10:10:35Z",
      "pushed_at": "2024-01-25T09:06:06Z",
      "git_url": "git://github.com/CloudInnovator/intall-test.git",
      "ssh_url": "git@github.com:CloudInnovator/intall-test.git",
      "clone_url": "https://github.com/CloudInnovator/intall-test.git",
      "svn_url": "https://github.com/CloudInnovator/intall-test",
      "homepage": null,
      "size": 27,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "private",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main"
    },
    "sender": {
      "login": "CloudInnovator",
      "id": 108559029,
      "node_id": "U_kgDOBnh6tQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/108559029?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CloudInnovator",
      "html_url": "https://github.com/CloudInnovator",
      "followers_url": "https://api.github.com/users/CloudInnovator/followers",
      "following_url": "https://api.github.com/users/CloudInnovator/following{/other_user}",
      "gists_url": "https://api.github.com/users/CloudInnovator/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CloudInnovator/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CloudInnovator/subscriptions",
      "organizations_url": "https://api.github.com/users/CloudInnovator/orgs",
      "repos_url": "https://api.github.com/users/CloudInnovator/repos",
      "events_url": "https://api.github.com/users/CloudInnovator/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CloudInnovator/received_events",
      "type": "User",
      "site_admin": false
    },
    "installation": {
      "id": 46143917,
      "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNDYxNDM5MTc="
    }
  }
}
```

**Comment by CloudInnovator** [comment]
Thanks. Will do
